### ISSUE TITLE
NullPointer Exception while setting the dev version

### ISSUE THREAD

**Issue by jerome-fosse** [shillner/unleash-maven-plugin#77] opened 2017-05-09 15:48 UTC
I have a null pointer exception with the unleash:perform goal. My build works fine but the unleash:perform goal goes on error while updating the new version number and commiting the changes. 

<pre><code>
INFO] 16:43:04,786  Removing artifact-spy-plugin from build configuration.
[INFO] 16:43:04,824  Checking remote SCM repository for changes. Initial revision was a469fdfdfdccbca6d0c34b2a041377dba57ad227
[DEBUG] 16:43:04,824  	No commit before tagging requested. Checking for SCM changes at this point unnessecary!
[INFO] 16:43:04,824  Tagging local and remote SCM repositories.
[DEBUG] 16:43:04,824  	Updating SCM connection tags in POM of module 'com.i.t:tok:3.2.0'
[DEBUG] 16:43:04,829  	Updating SCM connection tags in POM of module 'com.i.t:tok-security:3.2.0'
[DEBUG] 16:43:04,832  	Updating SCM connection tags in POM of module 'com.i.t:tok-data-jpa:3.2.0'
[DEBUG] 16:43:04,835  	Updating SCM connection tags in POM of module 'com.i.t:tok-common:3.2.0'
[DEBUG] 16:43:04,836  	Updating SCM connection tags in POM of module 'com.i.t:tok-test:3.2.0'
[DEBUG] 16:43:04,840  	Updating SCM connection tags in POM of module 'com.i.t:tok-application:3.2.0'
[DEBUG] 16:43:04,844  	Updating SCM connection tags in POM of module 'com.i.t:tok-sandbox:3.2.0'
[DEBUG] 16:43:04,846  	Updating SCM connection tags in POM of module 'com.i.t:tok-batch:3.2.0'
[DEBUG] 16:43:04,850  	Updating SCM connection tags in POM of module 'com.i.t:tok-client:3.2.0'
[INFO] 16:43:04,853  Git - Searching for Git tag 'release-3.2.0'
[DEBUG] 16:43:04,861  Git - Query info:
	- TAG_NAME: release-3.2.0
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
[DEBUG] 16:43:05,545  	Creating SCM tag with name 'release-3.2.0'. Tag will be created from local working copy.
[INFO] 16:43:05,546  Git - Tagging local repository with 'release-3.2.0'
[DEBUG] 16:43:05,546  Git - Tag info:
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- TAG_NAME: release-3.2.0
	- USE_WORKING_COPY: true
	- COMMIT_BEFORE_TAGGING: false
	- MERGE_STRATEGY: DO_NOT_MERGE
[INFO] 16:43:05,548  Git - Committing local changes.
[DEBUG] 16:43:05,746  Git - Commit info:
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- MERGE_STRATEGY: DO_NOT_MERGE
	- PUSH: false
	- COMMIT_ALL_CHANGES: true
[INFO] 16:43:06,430  Git - Commit finished successfully. New revision is: d963849080fbf9f462556b98b3be20ad55bfc463
[INFO] 16:43:08,704  Git - Tag creation finished successfully. New revision is: 
[INFO] 16:43:08,704  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
[DEBUG] 16:43:08,704  	Loading artifact-spy output of module 'com.i.t:tok:3.2.0' from /var/lib/jenkins/workspace/release_test/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,710  		The following artifact will be installed and deployed later: com.i.t:tok:pom:3.2.0
[DEBUG] 16:43:08,710  	Loading artifact-spy output of module 'com.i.t:tok-security:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-security/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,711  		The following artifact will be installed and deployed later: com.i.t:tok-security:pom:3.2.0
[DEBUG] 16:43:08,711  		The following artifact will be installed and deployed later: com.i.t:tok-security:jar:3.2.0
[DEBUG] 16:43:08,711  	Loading artifact-spy output of module 'com.i.t:tok-data-jpa:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-data-jpa/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,712  		The following artifact will be installed and deployed later: com.i.t:tok-data-jpa:pom:3.2.0
[DEBUG] 16:43:08,712  		The following artifact will be installed and deployed later: com.i.t:tok-data-jpa:jar:3.2.0
[DEBUG] 16:43:08,712  	Loading artifact-spy output of module 'com.i.t:tok-common:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-common/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,712  		The following artifact will be installed and deployed later: com.i.t:tok-common:pom:3.2.0
[DEBUG] 16:43:08,713  		The following artifact will be installed and deployed later: com.i.t:tok-common:jar:3.2.0
[DEBUG] 16:43:08,713  	Loading artifact-spy output of module 'com.i.t:tok-test:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-test/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,713  		The following artifact will be installed and deployed later: com.i.t:tok-test:jar:3.2.0
[DEBUG] 16:43:08,713  		The following artifact will be installed and deployed later: com.i.t:tok-test:pom:3.2.0
[DEBUG] 16:43:08,713  	Loading artifact-spy output of module 'com.i.t:tok-application:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-application/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,714  		The following artifact will be installed and deployed later: com.i.t:tok-application:pom:3.2.0
[DEBUG] 16:43:08,714  		The following artifact will be installed and deployed later: com.i.t:tok-application:jar:3.2.0
[DEBUG] 16:43:08,714  	Loading artifact-spy output of module 'com.i.t:tok-sandbox:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-sandbox/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,714  		The following artifact will be installed and deployed later: com.i.t:tok-sandbox:pom:3.2.0
[DEBUG] 16:43:08,714  		The following artifact will be installed and deployed later: com.i.t:tok-sandbox:jar:3.2.0
[DEBUG] 16:43:08,714  	Loading artifact-spy output of module 'com.i.t:tok-batch:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-batch/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,714  		The following artifact will be installed and deployed later: com.i.t:tok-batch:jar:3.2.0
[DEBUG] 16:43:08,715  		The following artifact will be installed and deployed later: com.i.t:tok-batch:pom:3.2.0
[DEBUG] 16:43:08,715  	Loading artifact-spy output of module 'com.i.t:tok-client:3.2.0' from /var/lib/jenkins/workspace/release_test/tok-client/target/artifact-spy/artifacts.properties
[DEBUG] 16:43:08,715  		The following artifact will be installed and deployed later: com.i.t:tok-client:pom:3.2.0
[DEBUG] 16:43:08,715  		The following artifact will be installed and deployed later: com.i.t:tok-client:jar:3.2.0
[INFO] 16:43:08,716  Preparing project modules for next development cycle.
[DEBUG] 16:43:08,716  	Preparing module 'com.i.t:tok:3.2.0'.
[DEBUG] 16:43:08,718  		Update of module version 'com.i.t:com.i.t:tok:pom:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,718  		Reversion of SCM connection tags
[DEBUG] 16:43:08,720  	Preparing module 'com.i.t:tok-security:3.2.0'.
[DEBUG] 16:43:08,721  		Update of module version 'com.i.t:com.i.t:tok-security:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,722  		Update of parent version of module 'com.i.t:com.i.t:tok-security:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,722  		Reversion of SCM connection tags
[DEBUG] 16:43:08,722  	Preparing module 'com.i.t:tok-data-jpa:3.2.0'.
[DEBUG] 16:43:08,724  		Update of module version 'com.i.t:com.i.t:tok-data-jpa:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,724  		Update of parent version of module 'com.i.t:com.i.t:tok-data-jpa:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,724  		Reversion of SCM connection tags
[DEBUG] 16:43:08,725  	Preparing module 'com.i.t:tok-common:3.2.0'.
[DEBUG] 16:43:08,726  		Update of module version 'com.i.t:com.i.t:tok-common:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,727  		Update of parent version of module 'com.i.t:com.i.t:tok-common:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,727  		Reversion of SCM connection tags
[DEBUG] 16:43:08,728  	Preparing module 'com.i.t:tok-test:3.2.0'.
[DEBUG] 16:43:08,729  		Update of module version 'com.i.t:com.i.t:tok-test:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,729  		Update of parent version of module 'com.i.t:com.i.t:tok-test:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,729  		Reversion of SCM connection tags
[DEBUG] 16:43:08,730  	Preparing module 'com.i.t:tok-application:3.2.0'.
[DEBUG] 16:43:08,732  		Update of module version 'com.i.t:com.i.t:tok-application:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,732  		Update of parent version of module 'com.i.t:com.i.t:tok-application:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,732  		Reversion of SCM connection tags
[DEBUG] 16:43:08,734  	Preparing module 'com.i.t:tok-sandbox:3.2.0'.
[DEBUG] 16:43:08,736  		Update of module version 'com.i.t:com.i.t:tok-sandbox:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,736  		Update of parent version of module 'com.i.t:com.i.t:tok-sandbox:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,736  		Reversion of SCM connection tags
[DEBUG] 16:43:08,737  	Preparing module 'com.i.t:tok-batch:3.2.0'.
[DEBUG] 16:43:08,738  		Update of module version 'com.i.t:com.i.t:tok-batch:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,738  		Update of parent version of module 'com.i.t:com.i.t:tok-batch:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,738  		Reversion of SCM connection tags
[DEBUG] 16:43:08,740  	Preparing module 'com.i.t:tok-client:3.2.0'.
[DEBUG] 16:43:08,741  		Update of module version 'com.i.t:com.i.t:tok-client:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT] Version Upgrade Strategy: MINOR
[DEBUG] 16:43:08,741  		Update of parent version of module 'com.i.t:com.i.t:tok-client:jar:3.2.0-SNAPSHOT' [3.2.0 => 3.3.0-SNAPSHOT]
[DEBUG] 16:43:08,741  		Reversion of SCM connection tags
[DEBUG] 16:43:08,742  	Committing changed POMs of all modules and pushing to remote repository. Merging with remote changes if necessary.
[INFO] 16:43:09,128  Git - Committing local changes.
[DEBUG] 16:43:09,135  Git - Commit info:
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- MERGE_STRATEGY: FULL_MERGE
	- PUSH: true
	- COMMIT_ALL_CHANGES: false
	- FILES: tok-application/pom.xml,tok-data-jpa/pom.xml,tok-security/pom.xml,tok-sandbox/pom.xml,tok-common/pom.xml,pom.xml,tok-test/pom.xml,tok-batch/pom.xml,tok-client/pom.xml
[INFO] 16:43:09,196  Git - Pushing local changes to remote repository.
[DEBUG] 16:43:09,196  Git - Push info:
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- LOCAL_BRANCH: a62f8c148ac5272c6678528debcec6fa63e67920
	- REMOTE_BRANCH: refs/heads/a62f8c148ac5272c6678528debcec6fa63e67920
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
	- MERGE_STRATEGY: FULL_MERGE

[INFO] 16:43:09,197  Git - Updating local repository with remote changes.
[DEBUG] 16:43:09,197  Git - Fetching remote updates.
[DEBUG] 16:43:09,198  Git - Fetch info:
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
[ERROR] An exception was caught while processing the workflow step with id 'setDevVersion'.
com.itemis.maven.plugins.unleash.scm.ScmException: No Git commit id found for String ''.
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:473)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.push(ScmProviderGit.java:373)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.commit(ScmProviderGit.java:337)
	at com.itemis.maven.plugins.unleash.util.DevVersionUtil.commitChanges(DevVersionUtil.java:100)
	at com.itemis.maven.plugins.unleash.steps.actions.SetNextDevVersion.execute(SetNextDevVersion.java:87)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.api.MergeCommand.include(MergeCommand.java:512)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:471)
	... 40 more
[INFO] Rolling back after execution errors - please find the error messages and stack traces above.
[INFO] 16:43:10,054  Rollback of all pom changes necessary for setting of the development version as well as reverting any made SCM commits.
[INFO] 16:43:10,069  Rollback of SCM tag creation and POM modifications due to a processing exception.
[INFO] 16:43:10,070  Git - Searching for Git tag 'release-3.2.0'
[DEBUG] 16:43:10,071  Git - Query info:
	- TAG_NAME: release-3.2.0
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
[DEBUG] 16:43:10,554  	Deleting scm tag 'release-3.2.0' since the release build failed.
[INFO] 16:43:10,554  Git - Deleting Git tag
[INFO] 16:43:10,556  Git - Searching for Git tag 'release-3.2.0'
[DEBUG] 16:43:10,557  Git - Query info:
	- TAG_NAME: release-3.2.0
	- WORKING_DIR: /var/lib/jenkins/workspace/release_test
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
[DEBUG] 16:43:10,881  Git - Tag info:
	- TAG_NAME: release-3.2.0
	- REMOTE: origin
	- REMOTE_URL: https://gitlab.sys.lab.ico.com/arc/tok.git
[INFO] 16:43:13,072  Rollback of artifact-spy-plugin addition to the build configuration.
[INFO] 16:43:13,077  Rollback of release version updating for all project modules
[DEBUG] 16:43:13,077  	Rolling back modifications on POM of module 'com.i.t:tok:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,078  	Rolling back modifications on POM of module 'com.i.t:tok-security:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,079  	Rolling back modifications on POM of module 'com.i.t:tok-data-jpa:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,079  	Rolling back modifications on POM of module 'com.i.t:tok-common:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,080  	Rolling back modifications on POM of module 'com.i.t:tok-test:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,080  	Rolling back modifications on POM of module 'com.i.t:tok-application:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,081  	Rolling back modifications on POM of module 'com.i.t:tok-sandbox:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,081  	Rolling back modifications on POM of module 'com.i.t:tok-batch:3.3.0-SNAPSHOT'
[DEBUG] 16:43:13,082  	Rolling back modifications on POM of module 'com.i.t:tok-client:3.3.0-SNAPSHOT'
[INFO] WELD-ENV-002001: Weld SE container STATIC_INSTANCE shut down
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping tok
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tok ....................................... FAILURE [03:03 min]
[INFO] tok-security .............................. SKIPPED
[INFO] tok-data-jpa .............................. SKIPPED
[INFO] tok-common ................................ SKIPPED
[INFO] tok-test .................................. SKIPPED
[INFO] tok-application ........................... SKIPPED
[INFO] tok-sandbox ............................... SKIPPED
[INFO] tok-batch ................................. SKIPPED
[INFO] tok-client ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:06 min
[INFO] Finished at: 2017-05-09T16:43:13+02:00
[INFO] Final Memory: 43M/285M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.4.2:perform (default-cli) on project tok: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.4.2:perform failed: No Git commit id found for String ''. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.4.2:perform (default-cli) on project tok: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.4.2:perform failed: No Git commit id found for String ''.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.4.2:perform failed: No Git commit id found for String ''.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
Caused by: com.itemis.maven.plugins.unleash.scm.ScmException: No Git commit id found for String ''.
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:473)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.push(ScmProviderGit.java:373)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.commit(ScmProviderGit.java:337)
	at com.itemis.maven.plugins.unleash.util.DevVersionUtil.commitChanges(DevVersionUtil.java:100)
	at com.itemis.maven.plugins.unleash.steps.actions.SetNextDevVersion.execute(SetNextDevVersion.java:87)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 32 more
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.api.MergeCommand.include(MergeCommand.java:512)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:471)
	... 40 more
</code></pre>

**Comment by shillner** [comment] 2017-05-10 05:46
Hi, I moved the bug to the Git SCM provider where the issue is caused: [unleash-scm-provider-git#9](https://github.com/shillner/unleash-scm-provider-git/issues/9)

Closing this one, please refer to the new issue!

**Closed as completed by shillner** 2017-05-10 05:46 UTC
Labels: bug
