### ISSUE TITLE
NullPointerException at com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform 

### ISSUE THREAD

**Issue by cloudyster** [shillner/unleash-maven-plugin#108] opened 2018-10-01 09:53 UTC
Hi, 
we've got a NullPointerException while running unleash:perform, Jenkins output/stacktrace is:

```
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform (default-cli) on project indra-dist: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform failed: WELD-000049: Unable to invoke public void com.itemis.maven.plugins.unleash.ReleaseMetadata.init() on com.itemis.maven.plugins.unleash.ReleaseMetadata@21f56109: InvocationTargetException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform (default-cli) on project indra-dist: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform failed: WELD-000049: Unable to invoke public void com.itemis.maven.plugins.unleash.ReleaseMetadata.init() on com.itemis.maven.plugins.unleash.ReleaseMetadata@21f56109
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:139)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:70)
    at hudson.remoting.UserRequest.perform (UserRequest.java:212)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:369)
    at hudson.remoting.InterceptingExecutorService$1.call (InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform failed: WELD-000049: Unable to invoke public void com.itemis.maven.plugins.unleash.ReleaseMetadata.init() on com.itemis.maven.plugins.unleash.ReleaseMetadata@21f56109
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:139)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:70)
    at hudson.remoting.UserRequest.perform (UserRequest.java:212)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:369)
    at hudson.remoting.InterceptingExecutorService$1.call (InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void com.itemis.maven.plugins.unleash.ReleaseMetadata.init() on com.itemis.maven.plugins.unleash.ReleaseMetadata@21f56109
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods (DefaultLifecycleCallbackInvoker.java:100)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct (DefaultLifecycleCallbackInvoker.java:81)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct (BasicInjectionTarget.java:126)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:171)
    at org.jboss.weld.context.AbstractContext.get (AbstractContext.java:96)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get (ContextualInstanceStrategy.java:101)
    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get (ContextualInstanceStrategy.java:141)
    at org.jboss.weld.bean.ContextualInstance.get (ContextualInstance.java:50)
    at org.jboss.weld.manager.BeanManagerImpl.getReference (BeanManagerImpl.java:742)
    at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference (BeanManagerImpl.java:842)
    at org.jboss.weld.injection.FieldInjectionPoint.inject (FieldInjectionPoint.java:92)
    at org.jboss.weld.util.Beans.injectBoundFields (Beans.java:363)
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers (Beans.java:374)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed (ResourceInjector.java:70)
    at org.jboss.weld.injection.InjectionContextImpl.run (InjectionContextImpl.java:48)
    at org.jboss.weld.injection.producer.ResourceInjector.inject (ResourceInjector.java:72)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject (BasicInjectionTarget.java:121)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:159)
    at com.itemis.maven.plugins.cdi.internal.util.CDIUtil.getAllBeansOfType (CDIUtil.java:71)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.getAllProcessingSteps (AbstractCDIMojo.java:327)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:203)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:139)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:70)
    at hudson.remoting.UserRequest.perform (UserRequest.java:212)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:369)
    at hudson.remoting.InterceptingExecutorService$1.call (InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods (DefaultLifecycleCallbackInvoker.java:98)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct (DefaultLifecycleCallbackInvoker.java:81)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct (BasicInjectionTarget.java:126)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:171)
    at org.jboss.weld.context.AbstractContext.get (AbstractContext.java:96)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get (ContextualInstanceStrategy.java:101)
    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get (ContextualInstanceStrategy.java:141)
    at org.jboss.weld.bean.ContextualInstance.get (ContextualInstance.java:50)
    at org.jboss.weld.manager.BeanManagerImpl.getReference (BeanManagerImpl.java:742)
    at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference (BeanManagerImpl.java:842)
    at org.jboss.weld.injection.FieldInjectionPoint.inject (FieldInjectionPoint.java:92)
    at org.jboss.weld.util.Beans.injectBoundFields (Beans.java:363)
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers (Beans.java:374)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed (ResourceInjector.java:70)
    at org.jboss.weld.injection.InjectionContextImpl.run (InjectionContextImpl.java:48)
    at org.jboss.weld.injection.producer.ResourceInjector.inject (ResourceInjector.java:72)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject (BasicInjectionTarget.java:121)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:159)
    at com.itemis.maven.plugins.cdi.internal.util.CDIUtil.getAllBeansOfType (CDIUtil.java:71)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.getAllProcessingSteps (AbstractCDIMojo.java:327)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:203)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:139)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:70)
    at hudson.remoting.UserRequest.perform (UserRequest.java:212)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:369)
    at hudson.remoting.InterceptingExecutorService$1.call (InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.itemis.maven.plugins.unleash.util.PomPropertyResolver.resolveAllProperties (PomPropertyResolver.java:111)
    at com.itemis.maven.plugins.unleash.util.PomPropertyResolver.expandPropertyReferences (PomPropertyResolver.java:70)
    at com.itemis.maven.plugins.unleash.ReleaseMetadata.init (ReleaseMetadata.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods (DefaultLifecycleCallbackInvoker.java:98)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct (DefaultLifecycleCallbackInvoker.java:81)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct (BasicInjectionTarget.java:126)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:171)
    at org.jboss.weld.context.AbstractContext.get (AbstractContext.java:96)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get (ContextualInstanceStrategy.java:101)
    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get (ContextualInstanceStrategy.java:141)
    at org.jboss.weld.bean.ContextualInstance.get (ContextualInstance.java:50)
    at org.jboss.weld.manager.BeanManagerImpl.getReference (BeanManagerImpl.java:742)
    at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference (BeanManagerImpl.java:842)
    at org.jboss.weld.injection.FieldInjectionPoint.inject (FieldInjectionPoint.java:92)
    at org.jboss.weld.util.Beans.injectBoundFields (Beans.java:363)
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers (Beans.java:374)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed (ResourceInjector.java:70)
    at org.jboss.weld.injection.InjectionContextImpl.run (InjectionContextImpl.java:48)
    at org.jboss.weld.injection.producer.ResourceInjector.inject (ResourceInjector.java:72)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject (BasicInjectionTarget.java:121)
    at org.jboss.weld.bean.ManagedBean.create (ManagedBean.java:159)
    at com.itemis.maven.plugins.cdi.internal.util.CDIUtil.getAllBeansOfType (CDIUtil.java:71)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.getAllProcessingSteps (AbstractCDIMojo.java:327)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:203)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main (Maven35Launcher.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at jenkins.maven3.agent.Maven35Main.launch (Maven35Main.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:139)
    at hudson.maven.Maven3Builder.call (Maven3Builder.java:70)
    at hudson.remoting.UserRequest.perform (UserRequest.java:212)
    at hudson.remoting.UserRequest.perform (UserRequest.java:54)
    at hudson.remoting.Request$2.run (Request.java:369)
    at hudson.remoting.InterceptingExecutorService$1.call (InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
[ERROR] 
```

**Comment by shillner** [comment] 2018-10-05 05:30
Hi, do you have some more details for me?

- plugin version
- pom setup
- ...

**Comment by cloudyster** [comment] 2018-10-05 06:11
Hello Stanley,

we use Jenkins' Unleash Maven Plugin Version 2.3.0, first line of
stacktrace (com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform)
indicates 2.8.0.
I'm not sure which is relevant for the issue.

Which information regarding pom setup do you need?

Yours,
Marc

**Comment by shillner** [comment] 2018-10-05 09:22
Hi, please try again with unleash-maven-plugin 2.9.3. This version should be on central in a few hours. Freitag, 05 Oktober 2018, 08:11vorm. +02:00 von cloudyster  notifications@github.com :

>Hello Stanley,
>
>we use Jenkins' Unleash Maven Plugin Version 2.3.0, first line of
>stacktrace (com.itemis.maven.plugins:unleash-maven-plugin:2.8.0:perform)
>indicates 2.8.0.
>I'm not sure which is relevant for the issue.
>
>Which information regarding pom setup do you need?
>
>Yours,
>Marc
>
>

**Comment by shillner** [comment] 2019-02-10 14:30
Closing this issue. Missing reaction leads to the assumption that the issue is fixed.

**Closed as completed by shillner** 2019-02-10 14:30 UTC
