### ISSUE TITLE
Ignore folder artifacts from java-build

### ISSUE THREAD

**Issue by ChristianLangmann** [shillner/unleash-maven-plugin#57] opened 2017-01-26 14:18 UTC
When using unleash:perform on an artefact-type that reuses language java, the spy collects an artifact with file ".../classes", which was created during the build.
This is written to the artifacts.properties and therefore is tried to be installed and deployed. But as the installation and deployment don't support folders, the step breaks und the unleash:perform fails.

My suggestion is to adjust the ArtifactSpy to ignore folders when adding project artifacts.

**Comment by shillner** [comment] 2017-01-26 18:07
Hi, thanks for the report but I didn't get it totally. Which packaging type do I have to set to reproduce this behavior? In case of "jar" it should work propperly. Can you post a minimal pom with the spy plugin configured that produces the properties with a folder path?
I'm just asking since I want to reproduce the behavior and check the fix before merging your PR ;)

**Comment by ChristianLangmann** [comment] 2017-01-27 10:59
I try to use unleash with Mule.
Mule has an own packaging type called mule, which is designed in plugin org.mule.tools:maven-mule-plugin:1.9 as


        
        <component>
            <role>org.apache.maven.artifact.handler.ArtifactHandler</role>
            <role-hint>mule</role-hint>
            <implementation>org.apache.maven.artifact.handler.DefaultArtifactHandler</implementation>
            <configuration>
                <type>mule</type>
                <language>java</language>
                <extension>zip</extension>
                <addedToClasspath>true</addedToClasspath>
            </configuration>
        </component>

I’ve created a github-repo which you can use to test the issue:

https://github.com/ChristianLangmann/unleash-test.git

Christian Langmann

**Comment by shillner** [comment] 2017-01-27 14:15
Hi, I merged your PR and included the new spy version in the plugin.
With unleash version 2.2.3 it should do.

**Closed as completed by shillner** 2017-01-27 14:15 UTC
