### ISSUE TITLE
Selective release of modules

### ISSUE THREAD

**Issue by whitewell188** [shillner/unleash-maven-plugin#113] opened 2019-01-23 20:02 UTC
Is it possible under the current plugin configuration to only release some of the modules from a multi-module maven project? Here is an example of what I am asking:

* Currently I have constructed a maven project with 14 modules
* Two of these modules build libraries (jars) upon which the other 12 apps (wars) depend
* If I alter the code in one of the libraries then I want to rebuild all 14 modules and release them all whilst retaining their individual module versions

As I understand it the unleash plugin supports this well already.

However:

* If I change code in one of the 12 apps I would like to release it alone from the project structure
* I would like the version of this released module to increase
* None of the other 11 apps need to be up-versioned or released, nor do the libs

In addition to this I would like to go further:

* In the jenkins plugin for unleash it already displays a table of the modules in a multi-module project (with their individual versions) though this appears to be for informational purposes only
* I would like there to be an additional column to this table with tick-boxes that allow me to selectively choose which module will be released

Is this a feature that you have considered before? I can see areas in the code where this could be added and would like your opinion on it if you have the time please.

Thanks

**Comment by shillner** [comment] 2019-01-24 08:21
Hi, thanks for using the plugin and your suggestions.

I guess your project setup is a bit unusual as there are kind of independent libraries and applications grouped together in one multimodule build. The workflow is clearly designed to always release all the modules together! Otherwise your SCM tag contains unreproducible state of the other modules that are still SNAPSHOT versions. Sure these modules are tagged but the dependencies to these modules are still SNAPSHOT-based.

However, as far as I remember your requested behaviour can be simulated by a small workaround (hope this still works). If you have a release version of your project (reactor and all modules are in released state) then you could branch from that tag and modify only the modules that are affected. Then the unleash plugin should only consider the modules that carry a SNAPSHOT version for release. E.g.:

**Your initial tag (0.1.0):**
parent: 0.1.0
  - libA: 0.2.0
  - libB: 0.1.3
  - appModule1: 0.1.0
  - appModule2: 0.1.0
  - app1: 0.1.0

**your branch for modification of libA only (starting from 0.1.0):**
parent: 0.1.0
  - libA: 0.3.0-SNAPSHOT
  - libB: 0.1.3
  - appModule1: 0.1.0
  - appModule2: 0.1.0
  - app1: 0.1.0

Then call unleash which should release only libA resulting in:
parent: 0.1.0
  - libA: 0.3.0
  - libB: 0.1.3
  - appModule1: 0.1.0
  - appModule2: 0.1.0
  - app1: 0.1.0

I'd be interested if this still works and how applicable this workflow is in real projects ;)

**Comment by whitewell188** [comment] 2019-01-24 15:40
Thanks for getting. back to me so quickly. Would I be right in saying 
that the workaround you mention here is based on the parameter 
"preserveFixedModuleVersions" which is described as "modules with fixed 
versions (release versions) shall be excluded during the version 
upgrading"? If I understand you correctly I think you are suggesting I 
could manipulate my version numbers so that the parameter above 
automatically excludes modules without the "-SNAPSHOT' suffix?

I had considered this but wondered if the configuration for the plugin 
could be more granular than that. Does the current plugin descend into 
each releasable module (i.e. with -SNAPSHOT) and perform the release 
process? i.e. multiple release cycles. If so I wondered if an optional 
parameter could hold a list of modules to release which would override 
the default behaviour. Or is there a way to write a workflow piece to do 
what I am looking for?

Thanks again.

Neal

**Comment by shillner** [comment] 2019-01-24 15:53
Yes this should be the parameter for that behavior. But there's currently no other mechanism to achieve a more selective behavior than that.

A custom action is always an option, e.g. to replace the version computation. This action can then be configured from outside to achieve your expected behavior.

If you propose a changed plugin implementation, I'll have to request a PR from you. Time is currently raw due to other projects an this plugin not being in focus right now.

But you could first try a custom action then. Maybe you can then contribute this action as well.

Thanks a lot.

**Comment by whitewell188** [comment] 2019-01-25 16:47
Can I just check if by "custom action" do you mean defining a custom 
workflow with a custom step?

**Comment by shillner** [comment] 2019-01-25 18:46
Right! Freitag, 25 Januar 2019, 05:47nachm. +01:00 von whitewell188  notifications@github.com :

**Comment by shillner** [comment] 2019-02-10 14:31
Closing as this feature won't be supported as part of the plugin. Please implement custom actions instead.
Thanks for the proposals.

**Closed as completed by shillner** 2019-02-10 14:31 UTC
