### ISSUE TITLE
Auto commit modified pom.xml files after pushing tag

### ISSUE THREAD

**Issue by XavierTalpe** [shillner/unleash-maven-plugin#51] opened 2016-10-26 13:29 UTC
Hey,

First of all, thanks for building this plugin! Saved me tons of work to add a release procedure to an existing Tycho project.

Currently when we run `mvn -B unleash:perform` we noticed that after committing the tag, the modified pom.xml's (with the new snapshot version) aren't committed. According to the logs an attempt does seem to be made to commit these files, but somehow it doesn't recognize the changes:

> [INFO] 15:26:14,669  Tagging local and remote SCM repositories.
> [INFO] 15:26:14,681  Git - Searching for Git tag 'lily-dsl-0.1.6'
> [INFO] 15:26:21,373  Git - Tagging local repository with 'lily-dsl-0.1.6'
> [INFO] 15:26:21,376  Git - Committing local changes.
> [INFO] 15:26:21,536  Git - Commit finished successfully. New revision is: 1f76a821e55b121c674b0c476aecfd2df7e0ad6f
> [INFO] 15:26:21,541  Git - Pushing local changes to remote repository.
> [INFO] 15:26:21,542  Git - Updating local repository with remote changes.
> [INFO] 15:26:24,857  Git - Update finished successfully. New revision is: 1f76a821e55b121c674b0c476aecfd2df7e0ad6f
> [INFO] 15:26:28,335  Git - Push finished successfully. New remote revision is: 1f76a821e55b121c674b0c476aecfd2df7e0ad6f
> [INFO] 15:26:28,336  Git - Tag creation finished successfully. New revision is: 1f76a821e55b121c674b0c476aecfd2df7e0ad6f
> [INFO] 15:26:28,336  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
> [INFO] 15:26:28,346  Preparing project modules for next development cycle.
> [INFO] 15:26:29,734  Git - Committing local changes.
> [INFO] 15:26:29,739  Git - Nothing to commit here.

To be clear, I'm talking about the following changes that are applied to our pom.xml's:

```
+    <version>0.1.7-SNAPSHOT</version>
+    <tag>HEAD</tag>
```

**Comment by shillner** [comment] 2016-10-26 13:48
Hi, can you try to setup a minimal example for me that shows this behavior?
Which versions are you using?

**Comment by XavierTalpe** [comment] 2016-10-26 13:51
I'm using version 2.1.3. In the meantime I noticed that releasing our Tycho project using `mvn -B unleash:perform-tycho` _does_ commit the modified pom.xml files. I'll have another look to see what might cause the problem. If I can reproduce this with a minimal example I'll let you know.

**Comment by XavierTalpe** [comment] 2016-10-27 15:25
Apparently this was caused by enabling the `commitBeforeTagging` flag in the configuration. Removing it solved my problem.

**Comment by shillner** [comment] 2016-10-27 15:50
Ok, I will investigate this, maybe tomorrow. Thanks for the report.  Donnerstag, 27 Oktober 2016, 05:25nachm. +02:00 von Xavier  notifications@github.com :

**Comment by shillner** [comment] 2016-10-28 11:31
Hi, sorry but I cannot reproduce this issue.
If I set the commitBeforeTagging flag the commit is created and pushed correctly to the remote repository.
Can you try to setup a minimal example for me?

**Comment by shillner** [comment] 2016-11-03 06:17
Closing this issue since I cannot reproduce the described behavior. Please test again with latest versions (2.1.1 of the plugin and 2.0.2 for the git provider) and reopen if the issue is still present.

**Closed as completed by shillner** 2016-11-03 06:17 UTC
