### ISSUE TITLE
Add support for POM-less tycho builds

### ISSUE THREAD

**Issue by winterer** [shillner/unleash-maven-plugin#98] opened 2017-12-13 12:29 UTC
At the momen, it seems the goal `unleash:perform-tycho` does not support POM-less tycho builds (e.g. http://blog.vogella.com/2015/12/15/pom-less-tycho-builds-for-structured-environments/).

When releasing such a project, we get the following exception:

```
[INFO] 13:11:24,917  Checking aether for already released artifacts of modules that are scheduled for release.
[INFO] 13:11:24,987  Updating project modules with release versions (POM and MANIFEST versions)
[ERROR] An exception was caught while processing the workflow step with id 'setReleaseVersionsTycho'.
org.apache.maven.plugin.MojoExecutionException: Error during tycho version upgrade.
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.execute (AbstractTychoVersionsStep.java:84)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetReleaseVersionsTycho.execute (SetReleaseVersionsTycho.java:30)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.io.FileNotFoundException: C:\projects\tycho-example\bundles\bundle1\pom.xml (The system cannot find the file specified)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:195)
    at java.io.FileInputStream.<init> (FileInputStream.java:138)
    at org.eclipse.tycho.versions.pom.MutablePomFile.read (MutablePomFile.java:66)
    at org.eclipse.tycho.versions.engine.ProjectMetadataReader.addBasedir (ProjectMetadataReader.java:63)
    at org.eclipse.tycho.versions.engine.ProjectMetadataReader.addBasedir (ProjectMetadataReader.java:69)
    at org.eclipse.tycho.versions.engine.ProjectMetadataReader.addBasedir (ProjectMetadataReader.java:69)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.execute (AbstractTychoVersionsStep.java:64)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetReleaseVersionsTycho.execute (SetReleaseVersionsTycho.java:30)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by shillner** [comment] 2017-12-13 16:41
Hi, it would be helpful if you could provide a minimal sample project.
Thanks.

**Comment by winterer** [comment] 2017-12-18 19:56
OK. Here you are: https://github.com/winterer/tycho-example-pomless

Unleashing this project with `unleash:perform-tycho` fails with the exception above due to a missing `pom.xml` in the plugin1 module, although this is NOT required due to tycho supporting POM-less builds via `tycho-pomless` extension (see folder `.mvn`).

However, I've also created a branch with a minimal `pom.xml` for the plugin1 module - now, the exception does not occure any more.

**Comment by shillner** [comment] 2017-12-19 12:47
Hi, thanks for the sample.
I've upgraded the tycho version that is used internally. This newer version now supports pom-less builds.
To get it running properly some other fixes were needed as well and especially the adaption rollback-feature was hard ;)

**Comment by winterer** [comment] 2017-12-21 20:54
Wow. Thanks for that quick response and fix!
Unfortunately, your fix seems to work partly only. I still get an exception telling that the file `.polyglot.build.properties` could not be found:

```
[INFO] 21:52:08,494  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
[ERROR] An exception was caught while processing the workflow step with id 'detectReleaseArtifacts'.
org.apache.maven.plugin.MojoExecutionException: Could not determine project release artifacts. Project: at.winterer.tycho:plugin1:0.0.1
    at com.itemis.maven.plugins.unleash.steps.actions.DetectReleaseArtifacts.execute (DetectReleaseArtifacts.java:86)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.io.FileNotFoundException: C:\projects\github\winterer\https\tycho-example-pomless\plugin1\.polyglot.build.properties (The system cannot find the file specified)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:195)
    at java.io.FileInputStream.<init> (FileInputStream.java:138)
    at com.google.common.io.Files$FileByteSource.openStream (Files.java:128)
    at com.google.common.io.Files$FileByteSource.openStream (Files.java:118)
    at com.google.common.io.ByteSource.copyTo (ByteSource.java:267)
    at com.google.common.io.Files.copy (Files.java:325)
    at com.itemis.maven.plugins.unleash.steps.actions.DetectReleaseArtifacts.execute (DetectReleaseArtifacts.java:76)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] Rolling back after execution errors - please find the error messages and stack traces above.
```

I've updated my [sample project](https://github.com/winterer/tycho-example-pomless) to also contain a feature and an update site.

**Comment by kevin-james-sp** [comment] 2018-01-26 01:44
I've just run into the same thing - could not find .polyglot.build.properties
I followed the article here: http://www.vogella.com/tutorials/EclipseTycho/article.html to set up a feature with multiple plugins (and update site), but I did create POMs (if that makes any difference; I only mention it because the original reporter was using pom-less tycho builds)

**Comment by shillner** [comment] 2018-01-26 06:58
Thanks for reporting. I'll have a look into it asap.

**Comment by kevin-james-sp** [comment] 2018-01-30 17:40
I think for the polyglot files it may be fixed by excluding them in the artifact-spy-plugin?

**Comment by Boereck** [comment] 2018-02-28 18:40
Hey, I am not sure if the problem I am facing at the moment is related. Currently I use the version 2.7.4. The build contains pom-less projects, but there are also other projects parts of the build. The build already fails in the root project:

[ERROR] An exception was caught while rolling back the workflow step with id 'setReleaseVersionsTycho'. Proceeding with the rollback of the next steps.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:259)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:238)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:161)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
Caused by: java.lang.NullPointerException
    at org.eclipse.tycho.versions.manipulation.AbstractMetadataManipulator.isBundle (AbstractMetadataManipulator.java:34)
    at org.eclipse.tycho.versions.manipulation.AbstractMetadataManipulator.isBundle (AbstractMetadataManipulator.java:30)
    at org.eclipse.tycho.versions.manipulation.BundleManifestManipulator.addMoreChanges (BundleManifestManipulator.java:38)
    at org.eclipse.tycho.versions.engine.VersionsEngine.apply (VersionsEngine.java:114)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.rollback (AbstractTychoVersionsStep.java:123)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetReleaseVersionsTycho.rollback (SetReleaseVersionsTycho.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:259)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:238)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:161)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)

**Comment by shillner** [comment] 2018-04-06 13:57
Hi, can you try again with the latest sources? Should work better now.

**Comment by shillner** [comment] 2018-04-13 10:11
Released version 2.8.0 with Issue resolved.

**Closed as completed by shillner** 2018-04-13 10:11 UTC

**Comment by kevin-james-sp** [comment] 2018-05-30 08:54
Finally got time to test it, and it works great! Thanks for fixing..

**Comment by kevin-james-sp** [comment] 2018-08-13 14:51
Maybe what I was experiencing wasn't related to this - I have just tried to do a release (my first using this method), and I get an error when the process tries to update the modules with a release version tag:

[INFO] 15:44:16,172  Removing artifact-spy-plugin from build configuration.
[INFO] 15:44:16,217  Checking remote SCM repository for changes. Initial revision was 95b78679043dfb4b7ebf65e2a3dd37a0c62ff81f
[INFO] 15:44:16,218  Tagging local and remote SCM repositories.
[INFO] 15:44:16,236  Git - Searching for Git tag '4.0.0'
[INFO] 15:44:18,336  Git - Tagging local repository with '4.0.0'
[INFO] 15:44:18,337  Git - Committing local changes.
[INFO] 15:44:23,228  Git - Commit finished successfully. New revision is: 458fa0f7902bf682a34a5e22c282fcbc192e9045
[INFO] 15:44:32,549  Git - Tag creation finished successfully. New revision is: 95b78679043dfb4b7ebf65e2a3dd37a0c62ff81f
[INFO] 15:44:32,550  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
[INFO] 15:44:33,345  Updating project modules with release versions (POM and MANIFEST versions)
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\bundles\sailpoint.IIQ_Deployment_Accelerator.core
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\bundles\sailpoint.IIQ_Deployment_Accelerator.identityiq
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\bundles\sailpoint.IIQ_Deployment_Accelerator.identitynow
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\bundles\sailpoint.IIQ_Deployment_Accelerator.plugins
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\bundles\sailpoint.IIQ_Deployment_Accelerator.logview
[INFO] No pom file found at E:\workspace-accelerator\IIQ_Deployment_Accelerator\features\sailpoint.IIQ_Deployment_Accelerator.feature
[ERROR] An exception was caught while processing the workflow step with id 'setDevVersionTycho'.
java.lang.NullPointerException
    at org.eclipse.tycho.versions.engine.VersionsEngine.getProject (VersionsEngine.java:167)
    at org.eclipse.tycho.versions.engine.VersionsEngine.getMutablePom (VersionsEngine.java:89)
    at org.eclipse.tycho.versions.engine.VersionsEngine.addVersionChange (VersionsEngine.java:81)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.execute (AbstractTychoVersionsStep.java:75)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetDevVersionsTycho.execute (SetDevVersionsTycho.java:57)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

**Comment by kevin-james-sp** [comment] 2018-08-13 18:00
I've also tried to use the sample project that winterer provided, but it won't build on my environment - I get the following error:

[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.7.4:perform-tycho (default-cli) on project tycho-example-pomless: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.7.4:perform-tycho failed: WELD-000049: Unable to invoke private void com.itemis.maven.plugins.unleash.util.DevVersionUtil.init() on com.itemis.maven.plugins.unleash.util.DevVersionUtil@3f2ae973: InvocationTargetException: No SCM provider found for SCM with name git. Maybe you need to add an appropriate provider implementation as a dependency to the plugin. One of setGitDir or setWorkTree must be called. -> [Help 1]
