### ISSUE TITLE
expose jenkins property like 'IS_M2RELEASEBUILD'

### ISSUE THREAD

**Issue by jorgheymans** [shillner/unleash-maven-plugin#94] opened 2017-11-07 14:29 UTC
Hi,

The m2release plugin exposes IS_M2RELEASEBUILD to allow a job to conditionally execute stuff before/after a release is being done. It would be nice if this plugin exposes 'IS_UNLEASHED' or something similar. For the moment i'm grabbing UNLEASH_SCM_USERNAME but i guess there could be a more explicit environment variable.

**Comment by shillner** [comment] 2017-11-08 07:37
There is also the request for it: [https://issues.jenkins-ci.org/browse/JENKINS-41766](https://issues.jenkins-ci.org/browse/JENKINS-41766).
I think I will spend some time on additional features somewhen the next time.

I'm closing this one since this is a duplicate of the Jenkins issue.

**Closed as completed by shillner** 2017-11-08 07:37 UTC
